apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-ca-secret
  labels:
    {{- include "labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Missing mkcert CA certificate '<chartdir>/mkcert/rootCA.pem', copy the file from mkcert's CA directory (mkcert -CAROOT)" (.Files.Get "mkcert/rootCA.pem") | b64enc }}
  tls.key: {{ required "Missing mkcert CA private key '<chartdir>/mkcert/rootCA-key.pem', copy the file from mkcert's CA directory (mkcert -CAROOT)" (.Files.Get "mkcert/rootCA-key.pem") | b64enc }}
