apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls-cert
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls-secret
  dnsNames:
  {{- range .Values.dnsNames }}
    - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ .Release.Name }}-tls-ca-issuer
    kind: Issuer